### ISSUE TITLE
Bar title not centered.

### ISSUE THREAD

**Issue by phocean** [andreyorst/Breezemite#15]
First, thanks for this wonderful theme. It is just awesome.

I have only one issue so far: the bar title is not exactly centered, it has some offset towards the left side.

![screenshot_20180111_144642](https://user-images.githubusercontent.com/4280885/34828582-4dc7b38c-f6de-11e7-9d77-95ad0f567ac8.png)

**Comment by andreyorst** [comment]
Oh. Well. Um... It's [centered](https://github.com/andreyorst/Breezemite/blob/31db2051c9a1d658dd0c81c91090d313272beaea/Breezemite_dark/Breezemite_darkrc#L16), kinda...
As i see you have borders, which mean that you're using modified version of breezemite. Maybe that's the case. Aurorae is really odd theming engine, it could possybly a bur or something else.
Anyway. I'm currently migrated to Gnome, so i can't tweak it for you because I have no KDE Plasma anymore. You can try new theme made by [this guy](https://github.com/ishovkun) called [SierrraBreeze](https://github.com/ishovkun/SierraBreeze).

**Comment by phocean** [comment]
Thanks for your answer, I will test all that.
It is your theme from this repo, I just selected a larger border in the configuration options.

By the way, it is funny: I am just coming from Gnome where I was exasperated by crashes.

Thanks again, you can close this issue if you wish.

**Comment by phocean** [comment]
Hmm, I think simply setting this solved the issue:

```
TitleBorderRight=0
```

Thanks.
