### ISSUE TITLE
Black edge on window border

### ISSUE THREAD

**Issue by lutracw** [andreyorst/Breezemite#16]
Hello. First, great work on this amazing theme. Absolutely love it.

And to the issue at hand:

My setup is displaying a black edge outside the window border. It extends just a tiny bit outside the border, and as a square corner up at the titlebar, where the theme is rounding. If this is a problem on my end, or your's I have no idea. I've tried un- and installing (via Get New Decoration under Application Style > Window Decorations > Theme in System Settings) without it being resolved.

I've attached a picture for illustration. The issue is for both Dark and normal theme.

![screenshot_20180116_130719](https://user-images.githubusercontent.com/8539609/34988836-71da678e-fac0-11e7-82eb-368350e6b9f8.png)

My settings are as follows:

Application Style > Window Decorations > Theme > Breezemite Dark

* Border size = Large
* Button size = Very Large

Workspace Theme > Look and Feel > Breeze
Workspace Theme > Desktop Theme > Breeze Dark

**Comment by andreyorst** [comment]
First of all there sould be blurred area if blur is turned on. Black edge is something new and looks like compositor error for me.
![image](https://user-images.githubusercontent.com/19470159/34989765-cced4376-fad4-11e7-9f7b-b91496c6f8cb.png)
This issue is related to #13. Please read my comment in that issue, and follow the links.

Shortly - i can't do much with this "edge" issue

**Comment by lutracw** [comment]
Haven't touched any settings about blur, so it should be its default value. 

Thanks, I'll have a look at #13 and see it I can get it to work for me too.
