### ISSUE TITLE
Icon for title bar Application Menu button is missing

### ISSUE THREAD

**Issue by trmdi** [andreyorst/Breezemite#5]
See the image below, it will use the icon of the application for the missing one:
![image](https://cloud.githubusercontent.com/assets/11857205/26030784/0c308332-3888-11e7-8f15-3697914c77a8.png)

**Comment by andreyorst** [comment]
Well... Yes, it is missing because the documentation is outdated and does not consist a name for this button. I will try to figure it out, but i still think that aurorae engine doesn't support this button, because the menu position in several themes are weird too.

and besides this is mac-style theme. It meant to use with global menu and buttons arranged to left :) 
![image](https://cloud.githubusercontent.com/assets/19470159/26033280/b90569b4-38b1-11e7-9b60-3ff9a19e0246.png)

**Comment by andreyorst** [comment]
I will try to do something in near furure.
