### ISSUE TITLE
Incorrect Application Menu position

### ISSUE THREAD

**Issue by trmdi** [andreyorst/Breezemite#6]
Please see the image below:
![image](https://cloud.githubusercontent.com/assets/11857205/26030801/a77ba20e-3888-11e7-8edc-a962027662d4.png)

**Comment by andreyorst** [comment]
Yes, already seen it. Trying to figure out whats up with coordinates. As there is no actual aurorae documentation, and one I've found is absolutely outdated it will take some time.

**Comment by andreyorst** [comment]
@trmdi, I've discovered that changing PaddingLeft and PaddingTop to zero fixes the issue, but the window decorations will gone under the window itself. So this is a aurorae bug, because padding shouldn't affect menu position. Unfortunately i don't know where to submit a bug about aurorae.
![image](https://cloud.githubusercontent.com/assets/19470159/26075214/2f3a4878-39bd-11e7-9957-f78c7555b24d.png)
I will try to fix it via editing svg files, but i dont sure how long it will take, i'm too busy right now

**Comment by andreyorst** [comment]
I will try to do something in near furure.
