### ISSUE TITLE
Missing Roll Up button

### ISSUE THREAD

**Issue by Bajoja** [andreyorst/Breezemite#7]
Missing the roll up button, when i add the roll up button to the title bar it not show, problably it missing some icon.

**Comment by andreyorst** [comment]
Hello, @Bajoja.
If you mean the shade button - it is disabled because aurorae has a bug with this button.
![default](https://cloud.githubusercontent.com/assets/19470159/26243975/8d729ed2-3c96-11e7-8e43-e97967a4b5d6.png)
If you still want to use this button, then remove dot from the beginning of the name ".shade.svg"

**Comment by Bajoja** [comment]
Thank you, i figured out wath the error after test it.
