### ISSUE TITLE
Oversized window borders on Plasma 5.10.1

### ISSUE THREAD

**Issue by ishovkun** [andreyorst/Breezemite#8]
An upgrade to Plasma 5.10.1 renders the theme ugly. The side window borders are huge even when
"Border size: No borders option" is set in the window decoration menu.
I will attach a screenshot if needed.

**Comment by andreyorst** [comment]
@ishovkun 5.10.1 Plasma's svg render kinda fucked up. I have some custom icons in my system, and after update some of them became too small, some of them became bigger than needed and pixelated (svg pixelated, huh...).

But you should know, that  "Border size: No borders" option does not affect aurorae themes at all, because aurorae theme engine gets information about bordersize from rc file in the theme directory.

Please upload a screenshot somewhere, because i've downgraded my Plasma and can't test it rightnow

**Comment by ishovkun** [comment]
Here goes the screenshot:
![screenshot_20170609_100815](https://user-images.githubusercontent.com/11154303/26981750-b2c74988-4cfb-11e7-83b7-4850fbe4821c.png)

**Comment by andreyorst** [comment]
Weeeeeeeeell... This is really interesting. I will update my plasma back and try to find a solution, but until then i ask you to try to change bordersize in `~/.local/share/aurorae/breezemite/breezemiterc` (if i remember the path right) like described in your previous [issue](https://github.com/andreyorst/Breezemite/issues/2#issuecomment-279088346)

By the way i'm planning to build this theme on same engine which breeze uses, to make this theme use system borders, button size and add a hiDPI support. Later in the summer, i hope.

**Comment by andreyorst** [comment]
@ishovkun You know, everything is ok on my archlinux, with new plasma.

**Comment by ishovkun** [comment]
Are you saying that your Arch is better than my Arch? :-)
Maybe I should install Breezemite from git not from KDE-store.
I will try your suggestion out when I get home and post an update.

**Comment by ishovkun** [comment]
So I tried breezemite from git. Same story.
I looked at the BorderLeft and BorderRight parameters: they are set to 0. When I increase those, the borders get thicker. Setting the parameters to negative values seems to have the same effect as setting them to 0.
Do you think some packages could have broken my aurorae? Maybe other suggestions? I have plasma 5.10.1 installed - the one that came out yesterday (06/08) in arch Extra repo.

**Comment by andreyorst** [comment]
if you confirm that everything is the same as here ![image](https://user-images.githubusercontent.com/19470159/27004300-829b196e-4e0f-11e7-9d38-5160b7a80db2.png)
then i might say that my arch is better then yours

**Comment by ishovkun** [comment]
![screenshot_20170610_233257](https://user-images.githubusercontent.com/11154303/27008387-404c5142-4e35-11e7-9ca3-77e5a7078c7e.png)

**Comment by andreyorst** [comment]
weird.
I will install arch on other laptop tomorrow, will test it.

**Comment by andreyorst** [comment]
@ishovkun everything is normal on clean install. I'm afraid i can't help you right now

> Linux is so flexible, that it repeats all the bends of the hands of its owner

WHAT A JOKE
Sorry, I could not resist....

**Comment by andreyorst** [comment]
@ishovkun did you received update to 5.10.2 today? DId anything changed?

**Comment by ishovkun** [comment]
No not yet. Gonna keep you posted.

**Comment by ishovkun** [comment]
Nothing's changed for me :-(

**Comment by LER0ever** [comment]
**Same here with Manjaro 17.0.1 Plasma 5.10.1**
![image](https://user-images.githubusercontent.com/10568668/27172425-dc8197d8-51e7-11e7-961b-177fd59d4aa5.png)
![image](https://user-images.githubusercontent.com/10568668/27172468-00165e04-51e8-11e7-94ad-3caf12955ee5.png)

**Comment by andreyorst** [comment]
So, the bug does reproduce, but no one can actually explain how. That's weird.
What about other aurorae themes?

**Comment by LER0ever** [comment]
> So, the bug does reproduce, but no one can actually explain how. 

I just had a fresh installation of Manjaro latest yesterday and had a full system upgrade (including plasma 5.10.1). Nothing else changes, no customization, no settings modifications. And Breezemite is installed via kde's "Get New Decorations". I would probably call this reproducible.

> Does clickable area of buttons is still in that colored circle, or it goes above of it? Maybe it is an issue with iconsize, which was rewritten in 5.10.1 plasma?

**The clickable area works perfectly. The thick border seems to be the drop shadow component? Maybe 5.10 handles shadows differently.**

**Comment by andreyorst** [comment]
> Maybe 5.10 handles shadows differently.

Shadows are part of the SVG file. In any case, I did not see anything about it in the change log.

> I just had a fresh installation of Manjaro latest yesterday and had a full system upgrade.
> I would probably call this reproducible.

Earlier in the morning i've reinstalled my arch on my laptop and as soon as possible tryed the theme from the store. Everything is fine. I will try this in Manjaro and probably Suse today, but i expect everything to by okay, because i've already tryed this on 3 laptops with archlinux on each. So I will call it reproducible if it will reproduce on any pc, and any distro, with plasma 5.10.1. 

I have asked my good friend to try this on his manjaro. Here are results:
![image](https://user-images.githubusercontent.com/19470159/27183577-adbf4972-51e7-11e7-9c4f-f572db049d87.png)
(He is from Ukraine)


Please try another themes, so we can figure out is it specific only to my theme, or it overall aurorae issue.
Bunch of themes to test:
[Yosemite](https://store.kde.org/p/1002637/) (which my theme was based on, so i expect same issue there)
[QTStep](https://store.kde.org/p/1176107/) 
[Arc KDE](https://store.kde.org/p/1167637/)

**Comment by LER0ever** [comment]
From what I see with Yosemite, (which is just terrable), **the color/image for the title bar gets replicated and tiled around the window to form that weird thick border**. Any idea on what may cause this issue?
![image](https://user-images.githubusercontent.com/10568668/27185384-bd1f3410-5217-11e7-96c3-d666f7688f0e.png)

**Comment by LER0ever** [comment]
Ahh, I think I've found out the cause. 

![image](https://user-images.githubusercontent.com/10568668/27185816-0ea03d1a-5219-11e7-8f18-b71c1986d4c0.png)

**This theme gets the border if HiDPI scaling is on.** 
My last screenshot was from 1.5x scale display. And after I turned off scale display, this decoration works just fine.

I don't know if this is still the issue of this decoration. After all, breeze works fine even under DPI scale.

**Comment by andreyorst** [comment]
> After all, breeze works fine even under DPI scale.

Breeze is **not** an aurorae theme.

For HiDPI support you might look at this issue: #4. There is not so much i can do about aurorae framework and HiDPI support.

**Comment by LER0ever** [comment]
> Breeze is not an aurorae theme.

Sorry I don't know much about theme dev, but Arc-KDE works fine under HiDPI scaling.
![image](https://user-images.githubusercontent.com/10568668/27186294-77e15ab0-521a-11e7-9f63-e9f3601a4469.png)

**Comment by ElliotSmith91** [comment]
Just want to confirm findings so far, also forcing fonts size to anything other than default increases the border size.

**Comment by andreyorst** [comment]
Well, that's what is interesting. I will experiment with this settings today.
@ElliotSmith91, thanks for useful information too

**Comment by ElliotSmith91** [comment]
The decoration used to be fine with changing font DPI from default, it seems Plasma 5.10.1 has changed something though.

Easiest fix for me at the moment has been changing font **size** to something readable for HiDPI screens and leaving scaling and force DPI setting in fonts at default.

I'm on KDE neon so people know :)

**Comment by ishovkun** [comment]
Thank y'all for figuring it out.
I completely forgot that I set the scaling up.

**Comment by iLynux8888** [comment]
So is this bug going to be fixed any time soon?

**Comment by andreyorst** [comment]
> Sorry I don't know much about theme dev, but Arc-KDE works fine under HiDPI scaling.
> ![image](https://user-images.githubusercontent.com/19470159/27984553-c15244ce-63e1-11e7-8f49-81fb43f98446.png)

Actually you're not quite right about "ark kde". The borders are got bigger too, but much more less then in my theme. I guess it's because they used something like a tool to create aurorae decorations, and as for me - I've done it by hands in inkscape, so i cant actually say what's wrong with my svg file, but as you can see below, borders are litle thinner then on schreenshot where HiDPI scaling is set to 1.5.
![image](https://user-images.githubusercontent.com/19470159/27984563-eef8b2fa-63e1-11e7-9c3a-41264518aaf8.png)

So, @iLynux8888, assuming this i can say that it is an a aurorae bug + my decorations are bit off too. I have a plan to remake this theme in qml, to bring somme extra features, but idk when i'll start.

**Comment by andreyorst** [comment]
I will try to do something in near furure.

**Comment by fedor1113** [comment]
So I use Breezemite Dark and can confirm that this theme always gets the invalid obscenely huge border if HiDPI scaling is on. A dumb workaround is to just change all padding values to ("original value"/"scaling factor") in the config. However, I found a surprising workaround for myself that **fully** negates this thing and removes the buggy behaviour until I change scaling again. **To correct it I just change the Desktop Theme in Plasma to something else and back again - and it works like a charm as before with any scaling!** This truly is an incredible bug! Fascinating actually... No idea how it interferes and interacts in this weird, strange way, but... hey it works in the end! Don't think it gives any ideas for the real solution - not straight away, anyway, but at least it would solve the problem much better than what people here have already suggested.

**Comment by hadig** [comment]
Borders are huge with only text dpi scaling

**Comment by felipunkz** [comment]
@hadig are right! the issue isn't with display scaling but with font scaling, untick the chekbox "Force fonts DPI", logout and it will be ok again!

**Comment by francoisboom23** [comment]
Hi
A recent bug that i found on my desktop but not on my laptop:
The title bar is a touch too small.
![image](https://user-images.githubusercontent.com/36674414/38260598-50d0b3ec-3768-11e8-9c9d-bb6ba1ffe33f.png)

Fix: borderleft and borderright set to 3
![image](https://user-images.githubusercontent.com/36674414/38260664-86cd258e-3768-11e8-9865-2663787abd09.png)
![image](https://user-images.githubusercontent.com/36674414/38260700-9e8a87fc-3768-11e8-85fe-072fadc66399.png)

![image](https://user-images.githubusercontent.com/36674414/38260496-0b532cf0-3768-11e8-8b2f-4d1746718e04.png)

**Comment by hadig** [comment]
[SierraBreeze Theme](https://aur.archlinux.org/packages/sierrabreeze-kwin-decoration-git) doesnt have this issue for people who really want to have osx buttons without the border issue. For example I have a 10inch screen with 1080p and for me disabling font scaling is not a solution

**Comment by andreyorst** [comment]
@hadig yes, this is stated in Readme
